@startuml

:Administrador: as Adm
:Actor Comun: as Act
:Cliente: as Cli
:Comercial: as Com

Adm --> (gestionar peticion)
Adm --> (realizar oferta)
Cli --> (visualizar ofertas)
Cli --> (consultar disponibilidad)
Act --> (consultar reservas)
Com --> (gestionar nueva reserva)

usecase UC1 as "      realizar oferta del comercial
--
     extension points
bloquear temporalmente una reserva"

(consultar) <|-- (consultar disponibilidad)
(consultar) <|-- (consultar reservas)
(realizar oferta) <|-- (UC1)
Cli <|-- Act
Act <|-- Com
Act <|-- Adm

(UC1) ..> (recalcular precio):<include>
(consultar) ..> (buscar elemento):<include>
(consultar disponibilidad) ..> (mostrar calendario):<include>

(bloquear temporalmente una reserva) ..> (UC1):<extend>

@enduml
