@startuml	
skinparam actorStyle Hollow
:Estudiante: --> (Consultar horarios)
:PDI: -up-> (Proponer cambios en los horarios)
:PAS: -left-> (Modificar horarios)
:PAS: -down-> (Dar de alta estudiantes)
Estudiante <|-- PAS
Estudiante <|-- PDI
:PAS: ..>(Validar datos) : <<include>>
usecase UC1 as "Dar de alta estudiantes
--
**extension points**
Buscar estudiantes en la lista de clase"
:PDI: --> (UC1)
(Buscar estudiantes en la lista de clase) ..> (UC1) : <<Extends>>
@enduml