@startuml
:Administrador: -->(eliminarProducto) 
:Comun:
Administrador--|>Comun
:Vendedor:
Vendedor --|> Comun
Comun -->(ConsultarPrecio)
Comun -->(ConsultarOferta)
(ConsultarPrecio)..>(BuscarProducto):<include>
:Proveedor: --|> Comun
Proveedor -->(AvisarFinDeOferta)

usecase UC1 as "AvisarDeNuevoProducto
--
**extension points**
IncorporarOferta"

Proveedor-->UC1
(IncorporarOferta)..>UC1:<extend>
(AvisarProveedor)..>(EnviarNotificacion):<include>
(AvisarFinDeOferta)..>(EliminarOferta):<include>
(AvisarFinDeOferta)--|>(AvisarProveedor)
(ConsultarProducto)--|>(BuscarProducto)
:Comprador: --> (ConsultarProducto)
(Agregar productos) as AgregarProductos
Comprador --> AgregarProductos
AgregarProductos ..> (Bloquear productos) : <<Include>>
(ConsultarProducto)..>(VerificarDisponibilidad):<include>
Comprador-->(FinalizarCompra)
Comprador-->(RealizarVenta)
(ConsultarHistorico)..>(RealizarVenta):<Extend>
(RealizarVenta)..>(AcordarPrecio):<include>
Vendedor-->(RealizarVenta)

@enduml