@startuml supuesto2E-R

entity "Producto"{
    * idProducto: number
    nombre: texto
    precio: number
    fechaIncorporacion : date
    stockDisponible : number
    precio : number
    enOferta : boolean
    fabricante : text
    modelo : text
    idProveedor : number <<FK>>
}

entity "Comprador"{
    * idComprador: number
    nombre: texto
    email : texto
    telefono : texto
}

entity "Cesta_de_la_compra"{
    * idProducto: number <<FK>>
    * idComprador: number <<FK>>
    unidades : number
}

entity "Productos_ofertados"{
    * idProducto: number <<FK>>
    * idOferta: number <<FK>>
}

entity "Vendedor"{
    * idVendedor: number
    nombre: texto
    email : texto
    telefono : texto
}

entity "Proveedor"{
    * idProveedor: number
    nombre: texto
    email : texto
    telefono : texto
}

entity "Oferta"{
    * idOferta: number
    nombre: texto
    fechaInicio: date 
    fechaFin: date 
    descuentoAplicable : number
    activa: boolean
}

entity "Notificacion"{
    * idNotificacion: number
    texto: texto
    fecha : date
    idAviso : number <<FK>>
    destinatario : text
}

entity "Venta" {
    * idProducto : number <<FK>>
    * idComprador: number <<FK>>
    * idVendedor: number <<FK>>
    fechaVenta: date
    precioVenta: number
    unidades : number
}

entity "Aviso" as Aviso {
    * idAviso : number
    fecha : date
    motivo : text
    destinatarios : text
    notificado : boolean
    idProveedor : number <<FK>>
}

entity "Administrador" as Administrador{
    * idAdministrador : number
    nombre : text
    email : text
    telefono : text
}

entity "Productos eliminados" as AEP{
    * idAdministrador : number <<FK>>
    * idProducto : number <<FK>>
}

entity "Productos bloqueados" as PB{
    * idComprador : number <<FK>>
    * idProducto : number <<FK>>
    unidades : number
}


Producto ||--|{ Cesta_de_la_compra
Cesta_de_la_compra }|--|| Comprador

Producto ||--|{ Productos_ofertados
Productos_ofertados }|--|| Oferta

Producto }|..|| Proveedor
Proveedor ||..|{ Aviso

Producto ||--|{ Venta
Venta }|--|| Vendedor
Venta }|--|| Comprador

Aviso ||..|{ Notificacion

Administrador ||--|{ AEP
AEP }|--|| Producto

Comprador ||--|{ PB
PB }|--|| Producto
