@startuml supuesto3E-R

entity "Reservas" as Reservas{
    * idReserva : number
    nombreCliente : text
    fechaInicio : date
    fechaFin : date
    habitacion : number
    numPersonas : number
    precio : number
}

entity "Reservas bloqueadas" as rb{
    * idReserva : number <<FK>>
    * idComercial : number <<FK>>
}

entity "Ofertas" as Ofertas{
    * idOferta : number
    nombre : text
    fechaInicio : date
    fechaFin : date
    precio : number
}

entity "Peticion" as Peticion{
    * idPeticion : number
    nombre : text
    fecha : date
    texto : text
}


entity "Comerciales" as Comerciales{
    * NIFComercial : number
    nombre : text
    edad : number
    empresa : text
}

entity "Administrador" as Administrador{
    * NIFAdministrador : number
    nombre : text
    edad : number
}


entity "Clientes" as Clientes{
    * NIFCliente : number
    nombre : text
    apellidos : text
    edad : number
    nacionalidad : text
}

entity "Habitaciones"{
    * nHabitacion : number
    planta : number
    numPersonas : number
    tipo : text
    disponibilidad : boolean
}


Comerciales ||--|{ Ofertas
Comerciales ||--|{ Reservas

Clientes ||--|{ Habitaciones
Clientes ||--|{ Peticion

Administrador ||--|{ Ofertas
Administrador ||--|{ Peticion

Reservas ||--|| Habitaciones

Comerciales ||--|{ rb
rb }|--|| Reservas


@enduml