@startuml supuesto1E-R

entity "Horario" as Horario{
    * idHorario : number
    nombre : text
    fechaIncorporacion: date
    * idGrupo : number <<FK>>
    * idCurso : number <<FK>>
}

entity "Estudiante" as Estudiante{
    * idEstudiante : number
    nombre: text
    fechaIncorporacion : date
    fechaNacimiento : date
    DNI : number
    email : text
    alta : boolean
}

entity "ListaDeClase" as ListaDeClase{
    * idListado : number
    nombreListado : text
    fechaIncorporacion : date
    nrEstudiantes : number
    idAsignatura : number <<FK>>
    idEstudiante : number <<FK>>
}

entity "Asignatura" as Asignatura{
    * idAsignatura : number
    nombre : text
    fechaIncorporacion : date
    nrEstudiantes : number
    profesor : text
    idCurso : number <<FK>>
}

entity "PDI" as PDI{
    * idPDI : number
    nombre : text
    fechaContratación : date
    email : text
    telefono : text
}

entity "PAS" as PAS{
    * idPAS : number
    nombre : text
    fechaContratacion : date
    email : text
    telefono : text
}

entity "Curso" as Curso{
    * idCurso : number
    coordinador : text
    * idGrado : number <<FK>>
}

entity "Grupo" as Grupo{
    * idGrupo : number
    * idCurso : number <<FK>>
}

entity "Grado" as Grado{
    * idGrado : number
    nombreGrado : text
    rama : text
    coordinador : text
    * idUniversidad : number <<FK>>
}

entity "Universidad" as Universidad{
    * idUniversidad : number
    nombre : text
    direccion : text
    nrTelefono : text
    email : text
    web : text
}

entity "Asignatura_horario" as AsHor{
    * idHorario : number <<FK>>
    * idAsignatura : number <<FK>>
    idClase : number <<FK>>
    hora : text
}

entity "Clase" as Clase{
    * idClase : number
    idUniversidad : number <<FK>>
    aforo : number
}

entity "Asignatura_PDI" as AsPDI{
    * idPDI : number <<FK>>
    * idAsignatura : number <<FK>>
}

PAS ||..|{ Estudiante
Estudiante }|..|| PDI

Estudiante ||..|{ ListaDeClase
ListaDeClase }|..|| Asignatura

Asignatura }|..|| Curso

Curso }|--|| Grado

Universidad ||--|{ Grado

Curso ||--|{ Grupo

Grupo ||--|| Horario

Horario ||--|{ AsHor
AsHor }|--|| Asignatura

Universidad ||--|{ Clase
Clase ||--|| AsHor

Asignatura ||--|{ AsPDI
PDI ||--|{ AsPDI



















@enduml